### ISSUE TITLE
Testing environment

### ISSUE THREAD

**Issue by Tereit** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-14-1#11]
Need some input on how we want the testing environment to work, specifically how the folder structure should work.
To get the *.spec.ts files to be compiled to .js files they need to be part of the paths the tsconfig.json file knows about. If we put the test files along with the components/modules/... we are testing then it works as is, but they then get compiled and included in the folder we publish from. If we want a separate test folder that can be set up so it's not included in the final build we need to do some work, either with the current folder structure or with the tsconfig.json files.
Any thoughts?

**Comment by henrikbossart** [comment]
no tests in production please...

**Comment by henrikbossart** [comment]
and if they are to be included, I would want them in a separate folder

**Comment by Tereit** [comment]
ok, then we have to restructure the whole folder structure, can't set tsconfig.json to compile to different folders

**Comment by henrikbossart** [comment]
Bring it up on the meeting, we'll discuss then
